name: boundless_immortality
description: Embark on a limitless journey of cultivation!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.4.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  go_router: ^14.8.1
  logging: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2

  firebase_core: ^3.12.1  # Needed for Crashlytics below
  firebase_crashlytics: ^4.3.4  # Error reporting
  games_services: ^4.0.3  # Achievements and leaderboards
  google_mobile_ads: ^5.3.1  # Ads
  in_app_purchase: ^3.2.1  # In-app purchases

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/icon/
